apiVersion: v1
kind: Pod
metadata:
  name: weekdayapp
spec:
  containers:
    - name: weekday
      image: praneeth200244/weekday_with_env_variables:latest
      ports:
        - containerPort: 80
      env:
        - name: DAY_NUMBER
          value: "5"  # Default value, can be changed dynamically later
