apiVersion: v1
kind: Pod
metadata:
  name: weekdayapp
spec:
  containers:
    - name: weekday
      image: praneeth200244/weekday_with_multistage:latest
      ports:
        - containerPort: 80
      args: ["5"]  # Example argument to print Friday (number 5)

